/**
 * spec/models.json → src/canvas/types.gen.ts
 *
 * Loose-but-useful TypeScript interfaces for Canvas response models. Every
 * property is optional because Canvas omits fields based on permissions and
 * `include[]` flags. Unknown/complex types fall back to `unknown`.
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

interface SpecModelProperty {
  type: string;
  description?: string;
  example?: unknown;
}
interface SpecModel {
  description?: string;
  properties: Record<string, SpecModelProperty>;
}

const specDir = path.resolve(import.meta.dirname, "../spec");
const outFile = path.resolve(import.meta.dirname, "../src/canvas/types.gen.ts");

function tsName(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
}

function tsType(t: string, known: Set<string>): string {
  const arr = /^Array<(.+)>$/.exec(t);
  if (arr) return `Array<${tsType(arr[1] ?? "unknown", known)}>`;
  switch (t.toLowerCase()) {
    case "string":
    case "datetime":
    case "date":
    case "url":
    case "uuid":
    case "text":
      return "string";
    case "integer":
    case "number":
    case "float":
    case "int64":
    case "int32":
    case "double":
      return "number";
    case "boolean":
      return "boolean";
    case "object":
    case "hash":
    case "json":
      return "Record<string, unknown>";
    default:
      return known.has(t) ? tsName(t) : "unknown";
  }
}

function safeKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
}

function doc(text: string | undefined, indent: string): string {
  if (!text) return "";
  const lines = text.split("\n").map((l) => `${indent} * ${l.replace(/\*\//g, "* /")}`);
  return `${indent}/**\n${lines.join("\n")}\n${indent} */\n`;
}

async function main() {
  const models = JSON.parse(await readFile(path.join(specDir, "models.json"), "utf8")) as Record<
    string,
    SpecModel
  >;
  const known = new Set(Object.keys(models));
  let out = "// Generated by scripts/gen-types.ts from spec/models.json. Do not edit.\n\n";
  for (const [name, m] of Object.entries(models)) {
    out += doc(m.description, "");
    out += `export interface ${tsName(name)} {\n`;
    for (const [pn, pv] of Object.entries(m.properties)) {
      out += doc(pv.description, "  ");
      out += `  ${safeKey(pn)}?: ${tsType(pv.type, known)};\n`;
    }
    out += "}\n\n";
  }
  await writeFile(outFile, out);
  console.log(
    `wrote ${Object.keys(models).length} interfaces to ${path.relative(process.cwd(), outFile)}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
