/**
 * Derive a compact, stable manifest from the raw Canvas spec snapshot.
 *
 *   spec/swagger12/*.json  →  spec/endpoints.json + spec/models.json
 *
 * The output format is the contract the rest of the repo depends on
 * (contract test, canvas_find_endpoint, gen-types). Swapping the *source* to
 * the OpenAPI 3 file generated by canvas-lms later only requires a new loader
 * in this script that produces the same shape.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

export interface SpecParam {
  name: string;
  in: "path" | "query" | "form" | "body" | "header";
  type: string;
  required: boolean;
  description?: string;
  enum?: string[];
  deprecated?: boolean;
}

export interface SpecEndpoint {
  /** HTTP method, upper case. */
  method: string;
  /** Full path including the `/api` prefix, path params in `{braces}`. */
  path: string;
  /** Swagger nickname (stable operation identifier). */
  nickname: string;
  /** Resource file stem, e.g. `courses`. */
  resource: string;
  summary: string;
  description?: string;
  params: SpecParam[];
  /** Response model name (or `Array<Model>`), when documented. */
  returns?: string;
  deprecated?: boolean;
}

export interface SpecModelProperty {
  type: string;
  description?: string;
  example?: unknown;
}

export interface SpecModel {
  description?: string;
  properties: Record<string, SpecModelProperty>;
}

interface RawParam {
  paramType: string;
  name: string;
  description?: string;
  type: string;
  format?: string | null;
  required?: boolean;
  deprecated?: boolean;
  enum?: string[];
  items?: { type?: string; $ref?: string };
}
interface RawOperation {
  method: string;
  summary: string;
  notes?: string;
  nickname: string;
  parameters: RawParam[];
  type?: string;
  items?: { type?: string; $ref?: string };
  deprecated?: boolean;
}
interface RawApi {
  path: string;
  description?: string;
  operations: RawOperation[];
}
interface RawModelProp {
  type?: string;
  $ref?: string;
  description?: string;
  example?: unknown;
  items?: { type?: string; $ref?: string };
}
interface RawModel {
  id: string;
  description?: string;
  properties: Record<string, RawModelProp>;
}
interface RawResourceDoc {
  resourcePath: string;
  apis: RawApi[];
  models?: Record<string, RawModel>;
}

const specDir = path.resolve(import.meta.dirname, "../spec");
const rawDir = path.join(specDir, "swagger12");
const MAX_DESC = 600;

function clip(s: string | undefined | null): string | undefined {
  if (!s) return undefined;
  const t = s.replace(/\r/g, "").trim();
  if (!t) return undefined;
  return t.length > MAX_DESC ? `${t.slice(0, MAX_DESC - 1)}…` : t;
}

function typeOf(t: unknown, items?: { type?: string; $ref?: string }): string {
  if (typeof t !== "string" || !t) return "unknown";
  if (t === "array") {
    const inner = items?.$ref ?? items?.type;
    return `Array<${typeof inner === "string" && inner ? inner : "unknown"}>`;
  }
  return t;
}

function paramIn(p: string): SpecParam["in"] {
  switch (p) {
    case "path":
    case "query":
    case "form":
    case "body":
    case "header":
      return p;
    default:
      return "query";
  }
}

async function main() {
  const files = (await readdir(rawDir)).filter((f) => f.endsWith(".json") && f !== "api-docs.json");
  const endpoints: SpecEndpoint[] = [];
  const models: Record<string, SpecModel> = {};

  for (const file of files.sort()) {
    const doc = JSON.parse(await readFile(path.join(rawDir, file), "utf8")) as RawResourceDoc;
    const resource = file.replace(/\.json$/, "");
    for (const api of doc.apis) {
      for (const op of api.operations) {
        const ep: SpecEndpoint = {
          method: op.method.toUpperCase(),
          path: `/api${api.path}`,
          nickname: op.nickname,
          resource,
          summary: op.summary,
          params: op.parameters.map((p) => {
            const sp: SpecParam = {
              name: p.name,
              in: paramIn(p.paramType),
              type: typeOf(p.type, p.items),
              required: Boolean(p.required),
            };
            const d = clip(p.description);
            if (d) sp.description = d;
            if (p.enum?.length) sp.enum = p.enum;
            if (p.deprecated) sp.deprecated = true;
            return sp;
          }),
        };
        const notes = clip(op.notes);
        if (notes && notes !== op.summary) ep.description = notes;
        if (op.type && op.type !== "void") ep.returns = typeOf(op.type, op.items);
        if (op.deprecated) ep.deprecated = true;
        endpoints.push(ep);
      }
    }
    for (const [name, m] of Object.entries(doc.models ?? {})) {
      if (models[name]) continue; // first definition wins; duplicates are identical in practice
      const props: Record<string, SpecModelProperty> = {};
      for (const [pn, pv] of Object.entries(m.properties ?? {})) {
        const prop: SpecModelProperty = { type: typeOf(pv.$ref ?? pv.type, pv.items) };
        const d = clip(pv.description);
        if (d) prop.description = d;
        if (pv.example !== undefined) prop.example = pv.example;
        props[pn] = prop;
      }
      const model: SpecModel = { properties: props };
      const d = clip(m.description);
      if (d) model.description = d;
      models[name] = model;
    }
  }

  // Stable ordering for reviewable diffs.
  endpoints.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
  const sortedModels = Object.fromEntries(
    Object.entries(models).sort(([a], [b]) => a.localeCompare(b)),
  );

  await writeFile(path.join(specDir, "endpoints.json"), `${JSON.stringify(endpoints, null, 1)}\n`);
  await writeFile(path.join(specDir, "models.json"), `${JSON.stringify(sortedModels, null, 1)}\n`);
  console.log(`endpoints: ${endpoints.length}, models: ${Object.keys(models).length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
