import { z } from "zod";
import { discussions } from "../canvas/services/student.ts";
import { paginationInput, verboseInput } from "./common.ts";
import { course, dryRunInput, entry, requestTool, text, topic } from "./request.ts";

export const discussionFields = [
  "id",
  "title",
  "message",
  "html_url",
  "posted_at",
  "last_reply_at",
  "discussion_type",
  "discussion_subentry_count",
  "read_state",
  "unread_count",
  "subscribed",
  "locked",
  "locked_for_user",
  "lock_explanation",
  "require_initial_post",
  "user_can_see_posts",
  "permissions",
  "assignment_id",
  "author",
  "is_announcement",
];
const entryFields = [
  "id",
  "user_id",
  "parent_id",
  "message",
  "created_at",
  "updated_at",
  "read_state",
  "rating_count",
  "rating_sum",
  "deleted",
  "replies",
  "recent_replies",
  "has_more_replies",
  "attachment",
];
const listInput = z.object({
  ...course,
  search_term: z.string().optional(),
  filter_by: z.enum(["all", "unread"]).optional(),
  ...paginationInput,
  verbose: verboseInput,
});
export const discussionTools = [
  requestTool({
    name: "canvas_discussions_list",
    toolset: "discussions",
    description: "List visible discussion topics in a course.",
    input: listInput,
    operation: discussions.list,
    list: true,
    fields: discussionFields,
    query: (a) => ({
      search_term: a.search_term,
      filter_by: a.filter_by,
      order_by: "recent_activity",
    }),
  }),
  requestTool({
    name: "canvas_discussions_subscribed_list",
    toolset: "discussions",
    description:
      "List subscribed topics from each fetched page. Filtering happens after pagination; an empty page may still have next_page_url.",
    input: listInput,
    operation: discussions.list,
    list: true,
    fields: discussionFields,
    query: (a) => ({ search_term: a.search_term, filter_by: a.filter_by }),
    filter: (value) => (value as Record<string, unknown>).subscribed === true,
  }),
  requestTool({
    name: "canvas_discussions_get",
    toolset: "discussions",
    description: "Read a discussion prompt as Markdown, with posting permissions and unread count.",
    input: z.object({ ...topic, verbose: verboseInput }),
    operation: discussions.get,
    fields: discussionFields,
  }),
  requestTool({
    name: "canvas_discussions_view",
    toolset: "discussions",
    description:
      "Read the full discussion thread, participants and unread entry IDs. Canvas may require an initial post before you can read replies.",
    input: z.object({ ...topic, verbose: verboseInput }),
    operation: discussions.view,
  }),
  requestTool({
    name: "canvas_discussions_entries_list",
    toolset: "discussions",
    description: "List top-level discussion entries as Markdown.",
    input: z.object({ ...topic, ...paginationInput, verbose: verboseInput }),
    operation: discussions.entries,
    list: true,
    fields: entryFields,
  }),
  requestTool({
    name: "canvas_discussions_entry_replies_list",
    toolset: "discussions",
    description: "List replies to one discussion entry.",
    input: z.object({ ...entry, ...paginationInput, verbose: verboseInput }),
    operation: discussions.replies,
    list: true,
    fields: entryFields,
  }),
  requestTool({
    name: "canvas_discussions_entry_post",
    toolset: "discussions",
    kind: "write",
    description: "Post a new top-level reply to a discussion. message accepts Canvas HTML.",
    input: z.object({ ...topic, message: text, dry_run: dryRunInput }),
    operation: discussions.post,
    fields: entryFields,
    body: (a) => ({ message: a.message }),
  }),
  requestTool({
    name: "canvas_discussions_entry_reply",
    toolset: "discussions",
    kind: "write",
    description: "Reply to a specific discussion entry. message accepts Canvas HTML.",
    input: z.object({ ...entry, message: text, dry_run: dryRunInput }),
    operation: discussions.reply,
    fields: entryFields,
    body: (a) => ({ message: a.message }),
  }),
  requestTool({
    name: "canvas_discussions_entry_update",
    toolset: "discussions",
    kind: "write",
    idempotent: true,
    description: "Edit your own discussion entry where Canvas permits editing.",
    input: z.object({ ...entry, message: text, dry_run: dryRunInput }),
    operation: discussions.update,
    fields: entryFields,
    body: (a) => ({ message: a.message }),
  }),
  requestTool({
    name: "canvas_discussions_entry_delete",
    toolset: "discussions",
    kind: "irreversible",
    idempotent: true,
    description: "Delete your own discussion entry where Canvas permits deletion.",
    input: z.object({ ...entry, dry_run: dryRunInput }),
    operation: discussions.delete,
  }),
  ...(
    [
      ["mark_read", discussions.read, "write"],
      ["mark_all_read", discussions.readAll, "write"],
      ["subscribe", discussions.subscribe, "write"],
      ["unsubscribe", discussions.unsubscribe, "irreversible"],
    ] as const
  ).map(([verb, operation, kind]) =>
    requestTool({
      name: `canvas_discussions_${verb}`,
      toolset: "discussions",
      kind,
      idempotent: true,
      description: `${verb.replaceAll("_", " ")} for this discussion topic on your account.`,
      input: z.object({ ...topic, dry_run: dryRunInput }),
      operation,
    }),
  ),
  requestTool({
    name: "canvas_discussions_rate_entry",
    toolset: "discussions",
    kind: "write",
    idempotent: true,
    description:
      "Like (1) or remove your like (0) on a discussion entry where ratings are enabled.",
    input: z.object({
      ...entry,
      rating: z.union([z.literal(0), z.literal(1)]),
      dry_run: dryRunInput,
    }),
    operation: discussions.rate,
    body: (a) => ({ rating: a.rating }),
  }),
];
