import { z } from "zod";
import { groups } from "../canvas/services/student.ts";
import { paginationInput, verboseInput } from "./common.ts";
import { dryRunInput, id, requestTool, text } from "./request.ts";

const groupFields = [
  "id",
  "name",
  "description",
  "is_public",
  "join_level",
  "members_count",
  "avatar_url",
  "context_type",
  "course_id",
  "group_category_id",
  "role",
  "leader",
  "permissions",
];
const userFields = ["id", "name", "short_name", "sortable_name", "avatar_url", "pronouns"];
const topicFields = [
  "id",
  "title",
  "message",
  "posted_at",
  "last_reply_at",
  "discussion_subentry_count",
  "read_state",
  "unread_count",
  "subscribed",
  "locked",
  "html_url",
];

export const groupTools = [
  requestTool({
    name: "canvas_groups_list_mine",
    toolset: "groups",
    description: "List the active Canvas groups you belong to.",
    input: z.object({
      context_type: z.enum(["Account", "Course"]).optional(),
      include_tabs: z.boolean().default(false),
      ...paginationInput,
      verbose: verboseInput,
    }),
    operation: groups.mine,
    list: true,
    fields: groupFields,
    query: (a) => ({
      context_type: a.context_type,
      include: a.include_tabs ? ["tabs"] : undefined,
    }),
  }),
  requestTool({
    name: "canvas_groups_get",
    toolset: "groups",
    description: "Get one visible group and your permissions in it.",
    input: z.object({
      group_id: id,
      include_tabs: z.boolean().default(false),
      verbose: verboseInput,
    }),
    operation: groups.get,
    fields: groupFields,
    query: (a) => ({ include: ["permissions", ...(a.include_tabs ? ["tabs"] : [])] }),
  }),
  requestTool({
    name: "canvas_groups_members",
    toolset: "groups",
    description: "List members visible in a group.",
    input: z.object({
      group_id: id,
      search_term: z.string().min(1).optional(),
      exclude_inactive: z.boolean().default(true),
      ...paginationInput,
      verbose: verboseInput,
    }),
    operation: groups.members,
    list: true,
    fields: userFields,
    query: (a) => ({ search_term: a.search_term, exclude_inactive: a.exclude_inactive }),
  }),
  requestTool({
    name: "canvas_groups_activity_stream",
    toolset: "groups",
    description: "List recent activity visible within a group.",
    input: z.object({ group_id: id, ...paginationInput, verbose: verboseInput }),
    operation: groups.activity,
    list: true,
    fields: ["id", "type", "title", "message", "created_at", "updated_at", "html_url"],
  }),
  requestTool({
    name: "canvas_groups_discussions_list",
    toolset: "groups",
    description: "List discussion topics in a group.",
    input: z.object({
      group_id: id,
      search_term: z.string().min(1).optional(),
      scope: z.enum(["locked", "unlocked", "pinned", "unpinned"]).optional(),
      ...paginationInput,
      verbose: verboseInput,
    }),
    operation: groups.discussions,
    list: true,
    fields: topicFields,
    query: (a) => ({ search_term: a.search_term, scope: a.scope }),
  }),
  requestTool({
    name: "canvas_groups_files_list",
    toolset: "groups",
    description:
      "List file metadata in a group. This does not download or extract document contents.",
    input: z.object({
      group_id: id,
      search_term: z.string().min(1).optional(),
      ...paginationInput,
      verbose: verboseInput,
    }),
    operation: groups.files,
    list: true,
    fields: [
      "id",
      "display_name",
      "filename",
      "content-type",
      "size",
      "created_at",
      "updated_at",
      "url",
      "locked",
      "hidden",
    ],
    query: (a) => ({ search_term: a.search_term }),
  }),
  requestTool({
    name: "canvas_groups_pages_list",
    toolset: "groups",
    description: "List wiki pages in a group, optionally including their Canvas HTML body.",
    input: z.object({
      group_id: id,
      search_term: z.string().min(1).optional(),
      include_body: z.boolean().default(false),
      ...paginationInput,
      verbose: verboseInput,
    }),
    operation: groups.pages,
    list: true,
    fields: [
      "page_id",
      "url",
      "title",
      "created_at",
      "updated_at",
      "published",
      "front_page",
      "body",
      "html_url",
    ],
    query: (a) => ({ search_term: a.search_term, include: a.include_body ? ["body"] : undefined }),
  }),
  requestTool({
    name: "canvas_groups_join",
    toolset: "groups",
    kind: "write",
    description:
      "Join or request to join a group, depending on its join level. Canvas returns an existing membership if already joined.",
    input: z.object({ group_id: id, dry_run: dryRunInput }),
    operation: groups.join,
    body: () => ({}),
  }),
  requestTool({
    name: "canvas_groups_invite",
    toolset: "groups",
    kind: "write",
    description:
      "Invite email addresses to a group when your group permissions allow it. This sends real invitation emails.",
    input: z.object({
      group_id: id,
      invitees: z.array(z.string().email()).min(1).max(50),
      dry_run: dryRunInput,
    }),
    operation: groups.invite,
    body: (a) => ({ invitees: a.invitees }),
  }),
  requestTool({
    name: "canvas_groups_discussion_post",
    toolset: "groups",
    kind: "write",
    description: "Post a message to a group discussion topic when members may post.",
    input: z.object({ group_id: id, topic_id: id, message: text, dry_run: dryRunInput }),
    operation: groups.post,
    fields: ["id", "user_id", "message", "created_at", "updated_at"],
    body: (a) => ({ message: a.message }),
  }),
  requestTool({
    name: "canvas_groups_leave",
    toolset: "groups",
    kind: "irreversible",
    idempotent: true,
    description:
      "Leave a group as the current user. Canvas may refuse groups that instructors do not allow students to leave.",
    input: z.object({ group_id: id, dry_run: dryRunInput }),
    operation: groups.leave,
  }),
];
